services:
  db:
    image: database
    build: database
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - online-store-network

  app:
    image: store
    build: store-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA-LOCATIONS=classpath:sql/schema.sql
      - SPRING_SQL_INIT_DATA-LOCATIONS=classpath:sql/data.sql
    networks:
      - online-store-network

networks:
  online-store-network:
    driver: bridge
