services:
  db:
    image: database
    build: database
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /docker-entrypoint-initdb.d
      - ./:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - online-store-network

  app:
    image: store
    build: store-backend
    depends_on:
      - db
    networks:
      - online-store-network
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  online-store-network:
    driver: bridge